# Generated by Django 3.2.11 on 2022-01-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_alter_share_symbol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share',
            unique_together={('symbol', 'portfolio')},
        ),
    ]
