version: '3'

services:
  db:
    image: "postgres"
    restart: on-failure:5
    env_file:
      - ./docker.env
    volumes:
      - postgres_db:/tmp/pgdata
    ports:
      - "5439:5432"

volumes:
    postgres_db:
